### ISSUE TITLE
WDS - trainer presentation

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Intelligent-analytics#13]
Slide 6 - Slide lists 4 customer needs, presenter notes list 5, trainer guide lists 6 - these should match

After Slide 16 - there is no slide for SMS messaging in the preferred solution section

Slide 17 - No presenter notes asking the Q&A Bot question that the slide is answering

Slide 20 - No presenter notes with question # 3 of Visualization & reporting that the slide is answering

**Comment by kylebunting** [comment]
Updates completed, where appropriate.

As to speaker's notes: These do not and should not match point-for-point what is on the slide, and they are not required on each slide. These are used where the explanation of the slide is not completely clear based on the text on the slide, or if elaborating comments are needed. Speaker’s notes are there to elaborate on the “minimal” text in the slide. In some cases, points on the slides or in the notes are combined or consolidated to save room and reduce the amount of text on the slide. The slides are a quick view that should be clean, whereas the speakers notes provide greater depth should a speaker need them for reference.
