### ISSUE TITLE
Re-arrange content for faster start

### ISSUE THREAD

**Issue by sebader** [microsoft/MCW-Intelligent-analytics#20]
After having worked through the MCW with a client, one very valid feedback point came back from the participants:
Exercise 1, the provisioning of Azure resources, should be split up so that only those resources are provisioned which are needed for a the very first start of the app. This brings participants much faster to a point where they get a feeling what is actually happening. Many of the resources from Exercise 1 are only needed (much) later:
- All of the cognitive Services
- Azure Search
- Stream Analytics
- CosmosDB
- API App

First step should be to set up the Web App, Function and one Event Hub and the Service Bus topic. Then move to the part to complete the first set of coding steps.
Once messages started to flow through the system, people started to understand much better the role each component was playing.
Overall the workshop was very well received, only the 2-3 hours of clicking through the Azure portal until something was finally start to show up, was perceived as too cumbersome.

**Comment by DawnmarieDesJardins** [comment]
Adding Kyle.  Please review and see if the August test/fix has addressed.  Thanks!

**Comment by mrfalafel** [comment]
No, the August-2018-testfix did not address this issue.

**Comment by mrfalafel** [comment]
These changes will take place for the October test-fix

**Comment by mrfalafel** [comment]
Moved the Power BI Provision to later in the step by step for the HOL.
Did not move the CosmosDB, Storage, Cognitive and Search provisions as they are needed early starting Exercise 2.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, address 10/2018
