### ISSUE TITLE
Change ChatMessageSentimentProcessorFunction to use ILogger or Tracewriter

### ISSUE THREAD

**Issue by sebader** [microsoft/MCW-Intelligent-analytics#21]
The Function code currently only uses Console.WriteLine() for output. This is not helpful at all since it will neither show up in the log stream nor in the AppInsights logging. Instead ILogger (.LogInformation(...)) or at least Tracewriter (.Info(...)) should be used.
In our workshop we had a few instances where participants misconfigured some step and it was hard to impossible to debug the Function in an easy way.
The output that is already foreseen to be printed using Console.WriteLine() is indeed very helpful - if it would shop up somewhere.

**Comment by DawnmarieDesJardins** [comment]
Test/fix complete - labelling this as an enhancement for next scheduled update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #49
