### ISSUE TITLE
Before the HOL

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Intelligent-analytics#22]
I've added the TOC from the template, but I can't get the TOC links to work. Please correct formatting.

**Comment by mrfalafel** [comment]
The links in the TOC work fine for me

**Comment by DawnmarieDesJardins** [comment]
Thanks Lino.  The Requirements and Before the hands-on lab shortcuts work, but the Task 1 & Task 2 shortcuts don't.  I'm sure it's something in my code but I can't quite figure out what I've done wrong.

**Comment by DawnmarieDesJardins** [comment]
I figured out how to get the link to Task 1 to work (remove capital letters), but I still can't get the link to Task 2 to work.  I suspect it has something to do with the parenthsis in the task title.  Please review and repair.


- [Intelligent analytics before the hands-on lab setup guide](#intelligent-analytics-before-the-hands-on-lab-setup-guide)
    - [Requirements](#requirements)
    - [Before the hands-on lab](#before-the-hands-on-lab)
        - [Task 1: Provision Power BI](#task-1-provision-power-bi)
        - [Task 2: Setup a lab virtual machine (VM)](#task-2-setup-a-lab-virtual-machine-(vm))

**Comment by mrfalafel** [comment]
Fixed the format of the first and second tasks in the MD for the links to work

**Comment by DawnmarieDesJardins** [comment]
Closing issue. QC complete, merging August test/fix to master
