### ISSUE TITLE
Unblock Web Essemblies

### ISSUE THREAD

**Issue by whaakman** [microsoft/MCW-Intelligent-analytics#26]
Make sure students are running the code from a local drive (not a OneDrive folder) and make sure all files are "unblocked" (Powershell -> gci -r |Unblock-File). This will prevent errors when publishing referring to "loadFromRemoteSources".

**Comment by DawnmarieDesJardins** [comment]
Test/fix complete - labelling this as an enhancement for next scheduled update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue. Was addressed in Jan 2020 update
