### ISSUE TITLE
Enhancement Required: Screenshots in the lab guide for provisioning the resources are mismatching with the Azure Portal.

### ISSUE THREAD

**Issue by Mayankbaweja105** [Microsoft/MCW-Intelligent-analytics#27]
Below are some examples with images for your reference:

1. In [Exercise 1, Task 7](https://github.com/Microsoft/MCW-Intelligent-analytics/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Intelligent%20analytics.md#task-7-provision-azure-cosmos-db), While adding Collection in Step 4, **Partition key** is added as a new field and there is no option for selecting Storage capacity as in the lab guide.
![image](https://user-images.githubusercontent.com/46557285/50960564-b353e280-14eb-11e9-940f-f46ff4b5d96a.png)

2. In [Exercise 6, Task 3](https://github.com/Microsoft/MCW-Intelligent-analytics/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Intelligent%20analytics.md#task-3-configure-staff-notifications), After selecting "  **Service bus-Bus - When a message is received in a queue (auto-complete)**  "in Step 4, Dialog box open is not same as mentioned in Lab guide. We have to enter a connection name and Service bus namespace or Service bus connection string by selecting _**_manually enter connection information_**_ enter for proceeding further to screenshot in lab guide.
![image](https://user-images.githubusercontent.com/46557285/50961962-201cac00-14ef-11e9-8268-2ae5e13aa183.png)

3. In [Exercise 5, Task 2](https://github.com/Microsoft/MCW-Intelligent-analytics/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Intelligent%20analytics.md#task-2-implement-linguistic-understanding), While publishing the app in Step 10, there is no option to select region and add key as per screenshot in lab guide. Also, when publishing complete, For end point URL, We have to go to **Keys and Endpoints** under Manage option in menu.
![image](https://user-images.githubusercontent.com/46557285/50964357-15fdac00-14f5-11e9-8292-dd271a31673e.png)

Similarly, Need to update the screenshots for Bing Speech API, Stream Analytics Job,Function app.

**Comment by DawnmarieDesJardins** [comment]
@Mayankbaweja105 
Thanks for bringing this to our attention!  This workshop is scheduled for an update soon, I'm labeling this to be reviewed at that time.

**Comment by DawnmarieDesJardins** [comment]
Thanks Mayankbaweja105.  I'm working on getting this reviewed for you.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, resolved with merge.  HTML files updated.
