### ISSUE TITLE
Not able to use Functions Bot app

### ISSUE THREAD

**Issue by himanshu311996** [microsoft/MCW-Intelligent-analytics#32]
In Exercise 9  Task 2 , i am not able to get Functions Bot app from Marketplace 

Please check on this and let us know the solution ASAP

Thanks

**Comment by timahenning** [comment]
Looks like the Functions Bot has recently been replaced by the AI - Web App Bot.

**Comment by himanshu311996** [comment]
@timahenning  Can you please update the lab guide accordingly? 

Thanks

**Comment by DawnmarieDesJardins** [comment]
Closing with recent test/fix merge.
