### ISSUE TITLE
 conciergePlusAppSearchApi not created

### ISSUE THREAD

**Issue by himanshu311996** [microsoft/MCW-Intelligent-analytics#33]
In Exercise 8 task 3 , task is to Copy the URL value of conciergePlusAppSearchApi, and paste it into the value setting for the chatSearchApiBase key, but as per Lab guide conciergePlusAppSearchApi is never created

**Comment by DawnmarieDesJardins** [comment]
@timahenning
Please review & advise.

**Comment by timahenning** [comment]
I look into that.

**Comment by timahenning** [comment]
The conciergePlusAppSearchApi is created in the beginning of the lab:

1. **Task 3: Create App Services** Step 9, under section ChatSearchApi

It is not named conciergePlusAppSearchApi.

**Comment by timahenning** [comment]
Closing.  Have not heard any feedback.
