### ISSUE TITLE
Service Bus queue output validation has changed.  Hyphens not allowed.

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Intelligent-analytics#34]
When I was going through the lab to debug another issue, I noticed that Service Bus queue names no longer accept hyphens in the name.  This causes an instruction dependency problem later when users need to create a message logger query.  This total breaks the lab.  It is a simple fix.

![image](https://user-images.githubusercontent.com/48766586/62332604-22d3f400-b475-11e9-90e8-8748a4e4a3f6.png)

![image](https://user-images.githubusercontent.com/48766586/62332620-2cf5f280-b475-11e9-8625-d56f9e1655fc.png)

**Comment by DawnmarieDesJardins** [comment]
Closing with recent test/fix merge.
