### ISSUE TITLE
Missing lab file

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Intelligent-analytics#37]
In hands on lab file app.Config is missing for the ChatMessageSentimentProcess Web Job project for the solution  (ConciergePlusSentiment.sln).
It is required as per Ex3: https://github.com/microsoft/MCW-Intelligent-analytics/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Intelligent%20analytics.md#exercise-3-configure-the-chat-web-app-settings

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by akn9050** [comment]
HI @timahenning, thanks for your response. Please let us know once you check and update.


Amit

**Comment by akn9050** [comment]
Any update on this please

**Comment by timahenning** [comment]
I will have an update by today.

**Comment by timahenning** [comment]
I just created the lab from scratch published without errors.  The instructions make reference to the Azure Function Application Settings set in previous 'Task 2: Configure the Chat Message Processor Function App'.  Web projects do not have App.config files, they have Web.config files.  I can see how the wording might be confusing.  There are no missing files.

**Comment by DawnmarieDesJardins** [comment]
Closing with recent merge.
