### ISSUE TITLE
Live Chat not working

### ISSUE THREAD

**Issue by himanshu311996** [microsoft/MCW-Intelligent-analytics#39]
In exercise 4 Task 3 while testing hotel lobby chat i am getting pop-up as error:undefined.
![error_2](https://user-images.githubusercontent.com/17895399/68310296-c4528d80-00d5-11ea-9e61-da7cab89532d.png)
![error_3](https://user-images.githubusercontent.com/17895399/68310308-c9174180-00d5-11ea-82e3-4a1519e7af49.png)

when i tried accessing website using IIS in visual studio i am not getting popup but i am not getting response in live chat

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by timahenning** [comment]
himanshu,

You have to wait a while for the message to be processed.  I would make sure your message made it to the Azure Web App.  I would also make sure the message made it Service Bus.

Tim

**Comment by DawnmarieDesJardins** [comment]
@himanshu311996 
Hello,
Please let us know if this issue has been resolved.

**Comment by srushti-714** [comment]
Hi @timahenning 

The messages are taking too much time (Almost an hour)  for the response.

**Comment by timahenning** [comment]
You are right.  That is entirely too long.  I am going through the lab myself at this moment.  I will write some code to flush the messages sooner.  It may be a few days before I post an update.

Tim

**Comment by timahenning** [comment]
@srushti-714 I just started working through the lab and found the messages were coming through without issue.  

![image](https://user-images.githubusercontent.com/48766586/69109393-79693c00-0a2c-11ea-9379-27550e252eda.png)

**Comment by timahenning** [comment]
I could not reproduce the errors above.
