### ISSUE TITLE
Before Hands-On Lab

### ISSUE THREAD

**Issue by LixarPeteK68** [microsoft/MCW-Intelligent-analytics#42]
Exercise 1, Task 9, step 13 mentions:

> Select Authorize. This will authorize the connection to your Power BI account. When prompted in the popup window, enter the account credentials you used to create your Power BI account in the Before the Hands-on Lab exercise. You may have to enter your Username and Password.

https://github.com/microsoft/MCW-Intelligent-analytics/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Intelligent%20analytics.md#task-9-create-stream-analytics-job

There is no mention of this on this page:
https://github.com/microsoft/MCW-Intelligent-analytics/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Intelligent%20analytics.md

**Comment by timahenning** [comment]
Thank you for the heads up.  I will update the BHOL.

Tim

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #44
