### ISSUE TITLE
Steps 23 and 24 for Linguistic Intelligence is wrong

### ISSUE THREAD

**Issue by DTessierLixar** [microsoft/MCW-Intelligent-analytics#43]
Step 23 and 24 of the linguistic intelligence is wrong:

"Type a new utterance in the text box.

The screenshot displays the sample value entered into the utterance text box.

Enter the following utterance:

Utterance: bring me toothpaste

Text to select: toothpaste

Entity: RoomService:RoomItem

Repeat this process for the following phrases (text to select is in bold):

Bring me towels | RoomService:RoomItem

Bring me blankets | RoomService:RoomItem

Order a soda | RoomService:FoodItem"

The RoomItem is tied to the Housekeeping entity NOT RoomService

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #45
