### ISSUE TITLE
powerbi workspace

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Intelligent-analytics#47]
In exercise7 task 1 , in powerbi user should get steps to create the **Myworkspace**, or it should be added in prerequisites

**Comment by timahenning** [comment]
My Workspace is the default workspace for Power BI for personal use.  You don't need to set it up.

Tim

**Comment by DawnmarieDesJardins** [comment]
No additional comments from field, closing as complete.  Can be reopened if needed.
