### ISSUE TITLE
Issues with lab instructions

### ISSUE THREAD

**Issue by andresu13** [microsoft/MCW-Intelligent-analytics#50]
Hi, I am planning to deliver this lab to one of my customers next week but I found a couple of issues with the lab guide/instructions. For example, Exercise 3 asks to create the following configuration keys:

ChatMessageSubscriptionName
ChatTopic
EventHubConnectionString
SourceEventHubName
ServiceBusConnectionString

However, for some of those keys, it is not clear what the values should be. I have found other issues with the lab that I would like to discuss with someone to fix and be able to present this to my customers. I am a FTE, can someone ping me internally to look at this?

Thank you!

**Comment by timahenning** [comment]
Hi Andres,

Go head list your issues.  I will look into them.

Tim

**Comment by andresu13** [comment]
Tim, can I setup sometime with you tomorrow to look at this together? My
internal Microsoft alias is anurruti.

Let me know.

Thanks,

Andres

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #51
